#!/usr/bin/env bash
#
# setup.sh -- build and publish the services app at services.shortlistone.com
#
#     cd ~/services-app && sudo bash setup.sh
#
# WHAT IT DOES
#   1. reads SUPABASE_URL, the anon key and ADMIN_EMAIL out of the ShortlistOne
#      source, and writes src/config.js -- so nothing has to be pasted, and the
#      two apps can never drift apart on which project they talk to
#   2. npm install && npm run build
#   3. publishes to /var/www/services
#   4. adds an nginx server block for services.shortlistone.com
#
# WHY IT READS THE KEY RATHER THAN ASKING FOR IT
# The anon key is public by design -- it already ships inside the ShortlistOne
# bundle. Extracting it avoids a 200-character paste that terminals and chat
# clients have mangled repeatedly. Note the declaration is line-wrapped in
# App.jsx, which is what defeated a naive grep earlier.
#
# BEFORE YOU RUN THIS
# services.shortlistone.com must already point at this server, or nginx will
# serve it and nobody will reach it. Check with:
#     dig +short services.shortlistone.com
# It should print this server's IP. If it prints nothing, add an A record at
# your DNS provider first and wait a few minutes.
#
# TLS is NOT set up here. Certbot needs the DNS to resolve first, so it is a
# separate step printed at the end.
#
# SAFETY
#   * never touches the existing ShortlistOne nginx config or /var/www/hr
#   * validates with nginx -t BEFORE reloading, and restores on failure
#   * idempotent

set -uo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HR_SRC="${HR_SRC:-/root/shortlisted/hr/hr/src/App.jsx}"
WEB_ROOT=/var/www/services
DOMAIN=services.shortlistone.com
CONF=/etc/nginx/sites-available/services

red()  { printf '\033[31m%s\033[0m\n' "$*"; }
grn()  { printf '\033[32m%s\033[0m\n' "$*"; }
info() { printf '  %s\n' "$*"; }

[ "$(id -u)" -eq 0 ] || { red "Run as root (sudo bash setup.sh)"; exit 1; }
[ -f "$HR_SRC" ] || { red "Can't find $HR_SRC — set HR_SRC=/path/to/App.jsx and re-run"; exit 1; }
[ -f "$APP_DIR/package.json" ] || { red "Run this from inside the services-app folder"; exit 1; }

# ------------------------------------------------------------- 1. config
echo "Reading Supabase config from ShortlistOne…"

# Both constants are line-wrapped in App.jsx: the value sits on the line AFTER
# the `const NAME =`. awk keeps reading until it sees the terminating line.
extract() {
  awk -v name="$1" '
    $0 ~ ("const " name " *=") { f=1 }
    f { buf = buf $0; if ($0 ~ /;[[:space:]]*$/ || $0 ~ /"[[:space:]]*;?[[:space:]]*$/) { print buf; exit } }
  ' "$HR_SRC" | grep -o '"[^"]*"' | head -1 | tr -d '"'
}

SUPA_URL=$(extract SUPABASE_URL)
SUPA_KEY=$(extract SUPABASE_ANON_KEY)
ADMIN=$(extract ADMIN_EMAIL)

[ -n "$SUPA_URL" ] || { red "Could not read SUPABASE_URL from $HR_SRC"; exit 1; }
[ ${#SUPA_KEY} -ge 100 ] || { red "Anon key looks wrong (length ${#SUPA_KEY}); expected 200+"; exit 1; }
[ -n "$ADMIN" ] || { red "Could not read ADMIN_EMAIL from $HR_SRC"; exit 1; }

info "url   $SUPA_URL"
info "key   ${SUPA_KEY:0:12}… (${#SUPA_KEY} chars)"
info "admin $ADMIN"

cat > "$APP_DIR/src/config.js" <<EOF
// Generated by setup.sh -- do not edit by hand; re-run setup.sh instead.
//
// The anon key is public by design: it ships in every client bundle and is
// useless without the RLS policies and column grants behind it. The service
// role key must NEVER appear in this file.
export const SUPABASE_URL = "$SUPA_URL";
export const SUPABASE_ANON_KEY = "$SUPA_KEY";
export const ADMIN_EMAIL = "$ADMIN";
EOF
grn "Wrote src/config.js"

# -------------------------------------------------------------- 2. build
echo
echo "Installing and building…"
cd "$APP_DIR" || exit 1
npm install --silent || { red "npm install failed"; exit 1; }
npm run build      || { red "build failed"; exit 1; }
grn "Built."

# ------------------------------------------------------------ 3. publish
mkdir -p "$WEB_ROOT"
rsync -a --delete "$APP_DIR/dist/" "$WEB_ROOT/"
grn "Published to $WEB_ROOT"

# -------------------------------------------------------------- 4. nginx
if grep -rq "server_name $DOMAIN" /etc/nginx/sites-enabled/ 2>/dev/null; then
  grn "nginx already serves $DOMAIN — leaving the config alone."
else
  echo
  echo "Adding an nginx server block for $DOMAIN…"
  BACKUP=""
  if [ -f "$CONF" ]; then
    BACKUP="/root/services-nginx.bak-$(date +%F-%H%M%S)"
    cp "$CONF" "$BACKUP"
    info "Backed up existing $CONF to $BACKUP"
  fi

  cat > "$CONF" <<NGINXCONF
# services.shortlistone.com -- the local services directory.
# A separate root from /var/www/hr; the hiring platform is untouched.
server {
    listen 80;
    server_name $DOMAIN;
    root $WEB_ROOT;
    index index.html;

    # Single-page app: unknown paths render the app, not a 404.
    location / {
        try_files \$uri \$uri/ /index.html;
    }

    # Hashed asset filenames, so they can be cached hard.
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
NGINXCONF

  ln -sf "$CONF" /etc/nginx/sites-enabled/services

  echo "Validating…"
  if ! nginx -t; then
    red "nginx rejected the config — undoing."
    rm -f /etc/nginx/sites-enabled/services
    [ -n "$BACKUP" ] && cp "$BACKUP" "$CONF"
    exit 1
  fi
  systemctl reload nginx || { red "Reload failed."; exit 1; }
  grn "nginx reloaded."
fi

# ------------------------------------------------------------- verify
echo
echo "Checking:"
DNS=$(dig +short "$DOMAIN" 2>/dev/null | tail -1)
if [ -z "$DNS" ]; then
  red "  $DOMAIN does not resolve yet."
  info "Add an A record for 'services' pointing at this server, then re-check."
else
  info "DNS -> $DNS"
  CODE=$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "http://$DOMAIN/" 2>/dev/null)
  if [ "$CODE" = "200" ]; then grn "  http://$DOMAIN/ -> 200"; else red "  http://$DOMAIN/ -> ${CODE:-no response}"; fi
fi

echo
grn "Done."
echo
info "NEXT — TLS (only once DNS resolves):"
info "    certbot --nginx -d $DOMAIN"
echo
info "Then open https://$DOMAIN, sign in with $ADMIN,"
info "and the Add and Manage tabs appear."
echo
info "To redeploy after any change:  cd $APP_DIR && npm run deploy"
